### ISSUE TITLE
Atualizar nossas infos no site PyLadies matriz

### ISSUE THREAD

**Issue by taniaa** [pyladiesdf/pyladiesdf_organizacao#1]
http://www.pyladies.com/locations/

**Comment by BrunaNayara** [comment]
Atualizei as infos e abri o PR
https://github.com/pyladies/pyladies/pull/398

**Comment by BrunaNayara** [comment]
PR aceito!

Porém, falta incluir: linkedin e instagram

**Comment by BrunaNayara** [comment]
Estamos live no site oficial!!! 
![image](https://user-images.githubusercontent.com/4125846/73542065-a8c7fc00-4412-11ea-86ff-d8e1eeb8342b.png)
[PR no reposiório oficial](https://github.com/pyladies/pyladies/pull/398)
