### ISSUE TITLE
Blusas para venda em eventos

### ISSUE THREAD

**Issue by silvasara** [pyladiesdf/pyladiesdf_organizacao#10]
Orçamento para blusas com logo da Pyladies para serem vendidas em eventos

**Comment by silvasara** [comment]
- Algodão: 25,00
- Poliéster: 20,00
- Prazo: 5 dias
**Disposto a cobrir orçamento**

- Babylooks:
      13 P; 16 M; 13 G; 8 GG;
- Nomal:
      13 P; 16 M; 13 G; 8 GG;
com essa estampa:
![image](https://user-images.githubusercontent.com/30883179/59041879-db9ffd00-884f-11e9-9100-5961beba2254.png)

contato: (61) 8188-05156 - Marcondes

**Comment by shayanealcantara** [comment]
### Manguezal Camiseteria (Guará 2)
Orçamento de 100 unidades (60  babylooks e 40 normais) 
- Malha-fria: 18,00
- Dry-fit: 20,00
- Algodão: 23,90

#### Prazo: 7 dias

Obs: Dispostos a cobrirem qualquer orçamento. Não fazem bottons e adesivos.
_Valores referentes aos tamanhos PP ao G. Acima desses valores, acrécimo de 20% por unidade._

Contato: 984027150 (Elisangelo) ou 992577795

**Comment by shayanealcantara** [comment]
### Raoni camisas gyn (Goiânia)
Mesmo tecido da camiseta do DG 2018

- Algodão penteado: 17,00

Contato: 62999664574
Obs: Necessário 2 semanas de antecedência.

**Comment by shayanealcantara** [comment]
### Estampa da Hora (Areal)

- Malha-fria, poliéster e anti-pilling: 20,00

**Comment by shayanealcantara** [comment]
### Smart Camisetas
_Para 60 unidades_
- Poliéster: 20,00
- Dry-fit: 25,00
- Algodão: 30,00

_Para 100 unidades_
- Poliéster: 18,00
- Dry-fit: 20,00
- Algodão: 25,00

Contato: 6182143951

**Comment by shayanealcantara** [comment]
### Padock Camisetas

- Malha-fria: 19,90
- Algodão: 25,90

Contato: 61999709526

**Comment by shayanealcantara** [comment]
### Arte e cores (Taguatinga)

- Malha-fria (com tratamento anti-pilling): 22,00 _com sublimação 18,00_
- Algodão: 25,00 

Contato: 991728561

**Comment by shayanealcantara** [comment]
### Estampa da Hora (Areal)

- Poliéster: 18,00
- Poliéster com anti-spilling e malha-fria: 20,00
- PV anti-spilling: 30,00
- Algodão: 35,00

Contato: 61984609834

**Comment by shayanealcantara** [comment]
### Sansar Camiseteria (Taguatinga)

_Para 100 unidades_
- Poliéster: 15,90 (básica) e 14,90 (Babylook)

Contato: 61996771855

**Comment by shayanealcantara** [comment]
### Virtual Brindes (Ceilândia)
_Para 100 unidades_

- Algodão: 19,90
- Malha-fria: 19,50
- DryFit: 30,00

#### Prazo: até 20 dias (em verificação se poderia ser menos)
 
Contato: 61 39638461

**Comment by BrunaNayara** [comment]
@shayanealcantara quais os prazos delas?

**Comment by BrunaNayara** [comment]
acho que essa ```Manguezal Camiseteria (Guará 2)``` é a melhor por enquanto, né?

**Comment by shayanealcantara** [comment]
@BrunaNayara atualizei os tópicos das empresas que responderam. Manguezal (7 dias) e Virtual Brindes estou esperando resposta se podem antecipar.

**Comment by silvasara** [comment]
@BrunaNayara tbm atualizei meu comentário
