### ISSUE TITLE
Arquivo de Apresentação da Comunidade

### ISSUE THREAD

**Issue by araandysilva** [pyladiesdf/pyladiesdf_organizacao#12]
Criar um arquivo texto apresentando a comunidade Pyladies DF com um tutorial do mostrando o organismo da comunidade (atividade, ferramentas, ações, issues, terefas, historia da Pyladies DF, fotos e etc)

**Comment by BrunaNayara** [comment]
Essa issue tá duplicada. Vou manter a #22 e adicionar essa descrição lá
