### ISSUE TITLE
Cursos Fábrica Social

### ISSUE THREAD

**Issue by lenamiroux** [pyladiesdf/pyladiesdf_organizacao#20]
- [ ] Descobrir o público-alvo
- [ ] Reunião para definir e montar os cursos
Requisitos: Trazer soluções para a comunidade, cursos com software livre, recursos acessíveis

**Comment by BrunaNayara** [comment]
A Fábrica social não respondeu nossos email, onde perguntávamos mais detalhes como datas, público e etc. Caso eles retornem o email, reabriremos essa issue
