### ISSUE TITLE
Dificuldades no Study Pyladies 

### ISSUE THREAD

**Issue by Sleshes** [pyladiesdf/pyladiesdf_organizacao#26]
No ano de 2019 a atividade de estudos tiveram algumas dificuldades que vou listar aqui para melhorarmos a atividade.

- Rotatividade de pessoa. A cada evento tinham pessoas diferentes o que dificulta a continuidade dos tópicos ou assuntos
- Iniciantes em python. Seria melhor ter um direcionamento mais delimitado para o acompanhamento dessas pessoas que tem geralmente a expectativa do aprendizado de formato de aula.
- Falta de monitores disponíveis compromete o acontecimento do evento (devido a isso a atividade ta suspensa)
- Há  pessoas que já tem algumas skills seria melhor focar em grupos para determinado assuntos

TODO:

- [x] Preparar que a atividade de estudo aconteça com mais regularmente 
- [x] Definir tópicos de aprendizado para guiar pessoas que são iniciantes em python
- [x] Montar material para iniciantes de python se guiarem (tópicos em python, cursos recomendados, links de materiais, recomendação de materiais)
- [x] Organizar grupos de estudo de acordo com interesses 
- [x]  Colocar os comentários de uma forma mais estruturada (criar pdf?)
- [x] disponibilizar o documento final e o de criação

**Comment by Sleshes** [comment]
Sugestão de Grupos de estudo:
- Estudo de Data Science no Geral
- Estudo de Análise de Dados (SQL e Python)
- Estudo de Python (iniciantes)
- outros?

**Comment by BrunaNayara** [comment]
[Curso de análise de dados do Masanori](https://github.com/fmasanori/CursoPyLadiesSP)
[Apresentações sobre Python do Luciano Ramalho](https://speakerdeck.com/ramalho/)
[Curso Python para Zumbis do Masanori](https://www.pycursos.com/python-para-zumbis/)
[Roadmap para desenvolvedores](https://roadmap.sh/)
[Colaboradados: Para iniciar em data science](http://colaboradados.com.br/blogposts/para-iniciar-em-data-science.html)
[Pizza de dados: indicações de data science](https://github.com/PizzaDeDados/datascience-pizza)

**Comment by BrunaNayara** [comment]
Achei mais um [Pycubator](https://github.com/grupydf/pycubator)
Tem esse curso que eu já fiz e é ótimo [Edx](https://courses.edx.org/courses/MITx/6.00.1x_5/1T2015/course)

**Comment by Sleshes** [comment]
Automate the Boring Stuff with Python By Al Sweigart
Livro online: https://automatetheboringstuff.com/
Curso online gratuito/desconto: Udemy Online Video Course com curso

**Comment by Sleshes** [comment]
Invent Your Own Computer Games with Python, 4th Edition
http://inventwithpython.com/invent4thed/

**Comment by BrunaNayara** [comment]
Esse material vai ser colocado em um repositório de dicas de material de estudo que a @fabiolamfleury vai criar. 
@fabiolamfleury se vc abrir e já colocar esses links aqui, pode fechar essa issue? Valeu :)
Se criar e não for colocar, pode marcar aqui alguém pra fazer e enviar o link dessa issue no grupo do telegram?

**Comment by fabiolamfleury** [comment]
Vou pegar aquele repositório da campus e separar bonitinho os assuntos, mudando o nome dele :) quando terminar fecho a issue!

**Comment by BrunaNayara** [comment]
Obrigada @fabiolamfleury

**Comment by fabiolamfleury** [comment]
Fiz o PR https://github.com/pyladiesdf/Materiais-de-Estudo/pull/1  


Sugerindo uma issue pra 'evoluir' essa issue: colocar um post no site das pyladies com esses referênciais, pra ficar numa interface mais amigável :)

**Comment by Sleshes** [comment]
Vou fechar essa issue e endereçar o assunto no repositório adequado
