### ISSUE TITLE
Criação do novo email

### ISSUE THREAD

**Issue by BrunaNayara** [pyladiesdf/pyladiesdf_organizacao#34]
Criar um email com `df`, atualmente o email é `brasília`

**Comment by Dayof** [comment]
O e-mail foi renomeado de ``brasilia@pyladies.com`` para ``df@pyladies.com``.

Sobre o alias ``brasilia@pyladies.com``:
"This user's previous email will automatically become an alternate email for the user. This ensures users continue receiving messages sent to previous emails."

Então ainda podemos receber mensagem pro ``brasilia@pyladies.com``, mas o ideal é que usemos o ``df@pyladies.com`` agora.

**Comment by BrunaNayara** [comment]
Com essa atualização, temos algumas coisas pra fazer que a Day colocou nessa outra issue #35
