### ISSUE TITLE
Atualizar nome e novo e-mail

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/pyladiesdf_organizacao#35]
Retirar todas as referências de ``PyLadies Brasília`` e atualizar para ``PyLadies DF``.

- [x] PyLadies Brasil (http://brasil.pyladies.com/locations/)
- [x] PyLadies Global (https://pyladies.com/locations/)
- [x] Site local (http://df.pyladies.com/)
- [x] Instagram (https://www.instagram.com/pyladiesdf/?hl=en)
- [x] Facebook (https://www.facebook.com/pyladiesdf)
- [x] GitHub (https://github.com/pyladiesdf)
- [x] Linkedin (https://www.linkedin.com/company/pyladies-df/)
- [x] Twitter (https://twitter.com/pyladiesdf)
- [x] Slack (https://pyladiesdf.slack.com)

**Comment by shayanealcantara** [comment]
O [PR](https://github.com/pyladies-brazil/br-pyladies-pelican/pull/368) das Pyladies Brasil foi aceito!
No aguardo para a aprovação e mudança no Global.

**Comment by shayanealcantara** [comment]
[PR](https://github.com/pyladies/pyladies/pull/528) global aceito. Fechando a issue
