### ISSUE TITLE
Orçamento de brindes 

### ISSUE THREAD

**Issue by BrunaNayara** [pyladiesdf/pyladiesdf_organizacao#9]
Fazer orçamento de 
- Bottons
- Stickers
- Canecas
- Garrafinhas

**Comment by BrunaNayara** [comment]
Essas duas artes podem ser para stickers e bottons. Atualizei e coloquei as artes de sticker do PyLadies global tbm 

![sticker-pyladies-1](https://user-images.githubusercontent.com/4125846/58978414-2400e180-87a2-11e9-8c60-8846faae2747.png)
![sticker-pyladies](https://user-images.githubusercontent.com/4125846/58978417-25320e80-87a2-11e9-8192-16968c8b016e.png)



![sticker-pyladies-rosa](https://user-images.githubusercontent.com/4125846/59044262-39364880-8854-11e9-804b-a7e2d4a5db9c.png)
![sticker-pyladies](https://user-images.githubusercontent.com/4125846/59044261-389db200-8854-11e9-9524-04c8dc76faef.png)

**Comment by BrunaNayara** [comment]
Pensei em usar esse padrão para fazermos garrafinhas, por exemplo. Ou canecas.
PS: Ele tá errado. Mas dá pra ter uma ideia. Vou atualizar ele masi tarde

![pyladies_seamless_pattern](https://user-images.githubusercontent.com/4125846/58981970-da1bf980-87a9-11e9-832b-bd9a36c342e0.png)

**Comment by shayanealcantara** [comment]
Foi criada uma issue com foco nas camisetas. #10

**Comment by danistvm** [comment]
Até amanhã finalizo orçamentos.

**Comment by shayanealcantara** [comment]
@danistvm @BrunaNayara Criei uma issue pro orçamento de adesivos #11
